### PR TITLE
Add $schema to JSON for better VSCode support

### PR DESCRIPTION
**Pull request by A5rocks**
I'm not completely sure adding `$schema` is fine, as this changes two (or more, because I may be missing spots) external things:
- adds `$schema` when you get a list's info
- maps the `$schema` ID to the invalid list ID `../schema/legacy.json` for stats posting due to how legacy mapping works -- but this is probably fine since the user could have just provided that URL anyways and `$schema` is an invalid list ID.

### CODE REVIEW

**Comment by MattIPv4** [comment]
👀 Does this require a small API change first to drop the `$schema` prop from the responses in `/api/lists`, `/api/lists/:list` and `/api/legacy-ids`?

**Comment by A5rocks** [comment]
It could do that (and I would be fine adding that) but really clients shouldn't care about the extra key.

**Comment by MattIPv4** [comment]
Clients probably wouldn't care about the extra key, but it would mean that the API schemas would be incorrect as the extra key would be present in the responses. I also don't think it makes much sense to be returning this key in the API responses as it's a relative path that wouldn't point to anywhere useful relative to the API.

**Comment by A5rocks** [comment]
https://github.com/botblock/api-worker/pull/4

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Pull request merged**
