### PR TITLE
Deleted some inactive lists

### PR DESCRIPTION
**Pull request by Ne-k**

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 Please do not delete inactive lists -- instead, simply set the `defunct` flag in each data file to `1`

**Comment by Ne-k** [comment]
Whoops, my bad.

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Looks like this PR still deletes `data/lists/automacord.xyz.json`

**Comment by Ne-k** [comment]
Odd, it was supposed to revert those changes.

**Review by MattIPv4 — APPROVED** [review]
LGTM, ty

**Pull request merged**
