### PR TITLE
Create botsdediscord.herokuapp.com.json

### PR DESCRIPTION
**Pull request by andrelucaas**

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Per https://botblock.org/lists/best-practices, we expect bot lists to have a custom domain and not be reliant on a domain provided by a free hosting provider (Heroku in this instance)

**Comment by andrelucaas** [comment]
Does my domain's subdomain, for example bdd.adgdev.me work?

**Comment by MattIPv4** [comment]
Yup :)

**Comment by MattIPv4** [comment]
No progress, closing.

**Pull request closed without merging**
