### PR TITLE
Update bhbotlist.tech API URLs + owners

### PR DESCRIPTION
**Pull request by anshtyagi0**

### CODE REVIEW

**Comment by A5rocks** [comment]
Note: this supersedes #52.

**Comment by anshtyagi0** [comment]
@MattIPv4 Please merge these changes

**Comment by MattIPv4** [comment]
@anshtyagi0 Please have some patience

**Comment by anshtyagi0** [comment]
sorry I thought you forgot to do that.

**Review by MattIPv4 — APPROVED** [review]

**Pull request merged**
