### PR TITLE
Update infinitybotlist.com

### PR DESCRIPTION
**Pull request by TheRealToxicDev**
- Updated domain to `infinitybots.gg` as this is now our primary domain for documentation, api and website usage. 

- Updated documentation link

Apologies should have made these changes with my pr the other day but didn’t even realize these still used the old domain!

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 As you are changing the id of the list, please can you also update the legacy ID mapping so that this doesn't break folks ability to use this list

**Comment by TheRealToxicDev** [comment]
> 👋 As you are changing the id of the list, please can you also update the legacy ID mapping so that this doesn't break folks ability to use this list

Ahh I was wondering what I did wrong. Will update this thanks!

**Comment by TheRealToxicDev** [comment]
> 👋 As you are changing the id of the list, please can you also update the legacy ID mapping so that this doesn't break folks ability to use this list

Alright I believe I have updated this. Not sure if you wanted me to remove the old domains or not as they still work just redirect to our new one so I just left them in place.

**Comment by TheRealToxicDev** [comment]
> You need to add an entry in https://github.com/botblock/data/blob/master/data/legacy.json to represent the renaming you are doing, and update any existing values of the id you are changing.

I did make a pr for that file just forgot to push it. Should be a separate PR for changes to it!

**Comment by MattIPv4** [comment]
You need to make it as a single PR, it will not pass tests as a separate PR.

**Comment by TheRealToxicDev** [comment]
> You need to make it as a single PR, it will not pass tests as a separate PR.

I was wondering if that’s why it was failing. Let me close these and I’ll make a new one!

**Pull request closed without merging**
